### PR TITLE
Update to be more flexible

### PR DESCRIPTION
**Pull request by quasibrodo**
After your email to me I discovered my edited code introduced a bug where the MIN and MAX Functions no longer worked with arguments that parenthesis. Such as MIN(2, (3*4)). I have since fixed that. 

Hopefully the comments in the gravityforms-minmax.js file make sense.

### CODE REVIEW

**Comment by georgemandis** [comment]
Thanks so much Bob. I'll review, test and merge assuming it all seems to be in working order.

**Comment by quasibrodo** [comment]
Sounds good! To be honest JS is probably my weakest language so, if you have more succinct or efficient ways to implement any of the changes I added, you wouldn't offend my ego one bit.

**Comment by quasibrodo** [comment]
Just letting you know in the regex patterns I was using I mistakenly used '\\' instead of '\/' so division in MIN and MAX functions looped indefinitely because the division sign wasn't matched and therefore the MIN or MAX function wasn't replaced.

I've fixed this in gravityforms-minmax.js and gravityforms-minmax.min.js

**Comment by georgemandis** [comment]
Hi Bob. I'm testing your pull request and when I'm editing a form in the backend and click "Preview" the page falls into a loop and just spins and spins. When I switch back to my current branch it loads as normal.

Are you seeing that?

**Comment by quasibrodo** [comment]
Not looking at it right now but I realized after the initial pull request that in the plugin there is also php that basically does the same thing as the js. I didn’t touch that as I didn’t know it existed. That’s probably the problem. If you want to try updating that go ahead. If not I’ll update it within the next couples weeks. I’ll need to do it for my client’s website I’m developing anyways.

**Comment by georgemandis** [comment]
Thanks! I genuinely appreciate it. I'll try to take a look this week.

**Comment by georgemandis** [comment]
Thanks @quasibrodo. I was still running into a bug where the form preview would fall into an infinite loop of some kind.

I just pushed a change to branch `v.0.4.0` here:
[https://github.com/snaptortoise/gravity-forms-minmax/tree/v0.4.0](https://github.com/snaptortoise/gravity-forms-minmax/tree/v0.4.0)

In my testing this approach seems to fix the issue with parentheses and also fixes the validation formula link (#1) in the editor.

Can you try that and let me know if it solved your problem? If it does, I'll merge it into master and update the plugin.

I came up with a slightly different solution that felt more maintainable, but I do appreciate you taking the time and helping me figure this out! It was very helpful.

**Comment by georgemandis** [comment]
I'm going to close this request because I'm pretty sure the latest merge addresses this issue. It also fixes issue #1 with validating formulas in admin.

Thanks for your help finding and troubleshooting the bug!

**Pull request closed without merging**
